Funcionario.create( name: 'Mathias Soares', function: 'Estagiário', salary: 1200.0)
Funcionario.create(name:'Danúbia Oliveira', function: 'Outros', salary: 1500.0)
Funcionario.create(name: 'Maria Jaqueline', function: 'Estagiário', salary: 1200.0)
Funcionario.create(name: 'Pablo Araújo', function: 'Gerente', salary: 1800.0)
Funcionario.create(name: 'Hernane Soares', function: 'Outros', salary: 1500.0)
